import { useRef } from "react";
import Head from "next/head";
import { Parallax, IParallax } from "@react-spring/parallax";
import { IntroductionSection, WorkSection } from "@/components";

export default function Home() {
  const parallax = useRef<IParallax>(null!);

  return (
    <>
      <Head>
        <title>Pichy.dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/favicon.ico" />
      </Head>
      <Parallax pages={3} style={{ top: "0", left: "0" }} ref={parallax}>
        <IntroductionSection parallax={parallax} />
        <WorkSection parallax={parallax} />
      </Parallax>
    </>
  );
}
